<?php
session_start();
include '../config/koneksi.php'; // Connect to the database

// Check session login
if (!isset($_SESSION['sudahLogin']) || !$_SESSION['sudahLogin']) {
    header('Location: ./login.php');
    exit();
}

// Get project ID from GET parameter
$id_proyek = isset($_GET['id_proyek']) ? intval($_GET['id_proyek']) : 0;

// Validate project ID
if ($id_proyek <= 0) {
    die("Invalid project ID.");
}

// Fetch project data from the database
$sql = "SELECT mp.*, l.status, l.progres, l.tanggal_mulai, l.tanggal_selesai 
        FROM manajemen_proyek mp 
        LEFT JOIN laporan l ON mp.id_proyek = l.id_proyek 
        WHERE mp.id_proyek = ?";
$stmt = $conn->prepare($sql);
$stmt->bind_param("i", $id_proyek);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows > 0) {
    $proyek = $result->fetch_assoc();
} else {
    die("Project not found.");
}

// Load TCPDF
require_once('../admin/vendor/autoload.php');
$pdf = new TCPDF();

// Set PDF metadata
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('SIDAPIT');
$pdf->SetTitle('Project Report');
$pdf->SetSubject('Project Report');
$pdf->SetKeywords('TCPDF, PDF, report, project');

// Set header and footer
$pdf->setHeaderData('', 0, 'Project Report', 'Generated by SIDAPIT');
$pdf->setFooterData(array(0, 64, 0), array(0, 64, 128));

// Set font
$pdf->SetFont('helvetica', '', 12);

// Add a page
$pdf->AddPage();

// Prepare HTML content
$html = '<h1>Project Details</h1>
<table border="1" cellpadding="4">
    <tr>
        <th>ID</th>
        <th>Nama Proyek</th>
        <th>Tanggal Mulai</th>
        <th>Tanggal Selesai</th>
        <th>Progress</th>
        <th>Status</th>
    </tr>
    <tr>
        <td>' . htmlspecialchars($proyek['id_proyek']) . '</td>
        <td>' . htmlspecialchars($proyek['nama_proyek']) . '</td>
        <td>' . htmlspecialchars($proyek['tanggal_mulai']) . '</td>
        <td>' . htmlspecialchars($proyek['tanggal_selesai']) . '</td>
        <td>' . (isset($proyek['progres']) ? htmlspecialchars($proyek['progres']) : 'No data') . '</td>
        <td>' . (isset($proyek['status']) ? htmlspecialchars($proyek['status']) : 'No data') . '</td>
    </tr>
</table>';

// Output HTML to PDF
$pdf->writeHTML($html, true, false, true, false, '');

// Clean output buffer before sending PDF
ob_end_clean(); // Clean the output buffer

// Output the PDF to the browser
$pdf->Output('laporan_proyek_' . $id_proyek . '.pdf', 'I'); // 'I' to display in browser, 'D' to download
?>